### ISSUE TITLE
relations one-to-one with None value

### ISSUE THREAD

**Issue by Meph-** [marshmallow-code/marshmallow-jsonapi#10]
Hi,
Is schema.dump() works, when relationship "author" is None? I need it for another database schema. Generaly some one-to-one, or many-to-one relationships may be None or null (db) and dump function should return something like:

    ....
    "relationship":{
        "author":{
            "data":null
        }
    }

right?

I have exception:

    data, errors = serializer.dump(post)
    File "C:\Python27\lib\site-packages\marshmallow\marshalling.py", line 140, in serialize
    index=(index if index_errors else None)
    File "C:\Python27\lib\site-packages\marshmallow\marshalling.py", line 63, in call_and_store
    value = getter_func(data)
    File "C:\Python27\lib\site-packages\marshmallow\marshalling.py", line 134, in <lambda>
    getter = lambda d: field_obj.serialize(attr_name, d, accessor=accessor)
    File "C:\Python27\lib\site-packages\marshmallow\fields.py", line 258, in serialize
    return self._serialize(value, attr, obj)
    File "C:\Python27\lib\site-packages\marshmallow_jsonapi\fields.py", line 88, in _serialize
    ret[attr]['links']['related'] = self.get_url(obj)
    File "C:\Python27\lib\site-packages\marshmallow_jsonapi\flask.py", line 39, in get_url
    kwargs = resolve_params(obj, self.url_kwargs)
    File "C:\Python27\lib\site-packages\marshmallow_jsonapi\utils.py", line 33, in resolve_params
    'attribute of {obj!r}'.format(attr_name=attr_name, obj=obj)
    AttributeError: 'author.id' is not a valid attribute of <app.models.post.Post object at 0x05721B70>

I think my proble is somewhere in function
    
    def _serialize(self, value, attr, obj):
    ...

where "value" is None and relationship id in "obj" is also None

What about:

    def _serialize(self, value, attr, obj):
        dict_class = self.parent.dict_class if self.parent else dict
        ret = dict_class()
        ret[attr] = dict_class()
        if value is not None: <---- new line
            ret[attr]['links'] = dict_class()
            ret[attr]['links']['related'] = self.get_url(obj)
            if self.include_data:
                ret[attr]['data'] = self.add_resource_linkage(value)
        return ret

https://github.com/marshmallow-code/marshmallow-jsonapi/blob/master/marshmallow_jsonapi/fields.py

**Comment by sloria** [comment]
Thanks for reporting @Meph- . I would consider this a bug, and I think your proposed solution--returning an empty `dict`--is a fine solution. 

Would you like to send a PR for this? If not, I'll try to get to this within the next few days.
