### ISSUE TITLE
Load schema with only=str gives empty UnmarshalResult 

### ISSUE THREAD

**Issue by erlingbo** [marshmallow-code/marshmallow-jsonapi#13]
When using a schema with the only attribute set to a string, the load method returns UnmarshalResult without errors nor data.

```
class MySchema(Schema):
    class Meta:
        fields = ('pk',)

    pk = fields.String()

MySchema(only='pk').load('an_id1234')
MySchema(only='pk').load({'pk': 'an_id1234'})
```

Both return the same UnmarshalResult
`UnmarshalResult(data={}, errors={})`

Preferably the first should work, but the second could be used with a pre load method on the schema class.

Is there anything I have done wrong or is this a bug?

**Comment by jklapuch** [comment]
Change

```
 only="pk"
```

with

```
only=["pk"]
```

and the second will work. The first will return:

```
UnmarshalResult(data={}, errors={u'_schema': [u'Invalid input type.']})
```

**Comment by erlingbo** [comment]
yes, it will, but then dump will give me a different result, and thus not solve my probem

**Comment by jklapuch** [comment]
Other then this?

```
MySchema(only=["pk"]).dump({'pk': u'an_id1234'})
Out: MarshalResult(data={'pk': u'an_id1234'}, errors={})
```

**Comment by erlingbo** [comment]
I see that I posted this in the json-api repo. Should have been in the original marshmallow project. Will close this and reopen it in the correct project.

https://github.com/marshmallow-code/marshmallow/issues/307
