### ISSUE TITLE
Passing something that isn't a dict (like None) into load causes an unhandled exception

### ISSUE THREAD

**Issue by grantHarris** [marshmallow-code/marshmallow-jsonapi#148]
Passing something that isn't a dict into load or validate causes an unhandled AttributeError.

`AttributeError: 'NoneType' object has no attribute 'get'`

The library should handle this and raise a proper validation error instead.

**Comment by sloria** [comment]
@grantHarris What version of marshmallow are you using? marshmallow 3.0.0 (beta) changed the behavior for loading `None` so that it raises a `ValidationError`.

**Comment by grantHarris** [comment]
2.15.3

**Comment by sloria** [comment]
Ah ok. This is a known issue with marshmallow 2 (https://github.com/marshmallow-code/marshmallow/issues/511), so there's nothing to be done in this project.
