### ISSUE TITLE
Version 0.20.4 is not published on pypi

### ISSUE THREAD

**Issue by kumy** [marshmallow-code/marshmallow-jsonapi#175]
I can't find version 0.20.4 on pypi https://pypi.org/project/marshmallow-jsonapi/

And pip install say
`No matching distribution found for marshmallow-jsonapi==0.20.4 (from -r requirements/common.txt (line 3))`

**Comment by sloria** [comment]
Ah, it looks like the build that was supposed to release 0.20.4 failed. I restarted it and it's now on PyPI. Sorry for the hiccup and thanks for bringing this to my attention.
