### ISSUE TITLE
marshmallow-jsonapi as argmap/schema for webargs parser

### ISSUE THREAD

**Issue by jo-tham** [marshmallow-code/marshmallow-jsonapi#18]
I tried to use a marshmallow-jsonapi schema for webargs parser and get the following errors

I am trying this, but 

```
> curl -i -H "Content-type:application/json" -X POST -d '{ "data": { "attributes": { "nickname": "two" }, "type": "user" }}' http://localhost:5000/api/v1/users
HTTP/1.0 422 UNPROCESSABLE ENTITY
Content-Type: application/json
Content-Length: 146
Content-Length: 215
Server: Werkzeug/0.10.4 Python/3.5.0
Date: Sun, 22 Nov 2015 00:35:08 GMT

{
    "message": {
        "errors": [
            "Object must include `data` key."
        ]
    },
    "status": 422,
    "title": "Invalid"
}
```

Any suggestions?

**Comment by jo-tham** [comment]
`request.json` is parsed with the `marshmallow.jsonapi schema`

the schema does not define the first level objects (data, realtionships) as fields, the result of `request.json` parsing is then several marshmallow.missing fields

eventually, this is loaded into the schema, at which point it fails because the `marshmallow.jsonapi schema pre_load` expects `data` as a top level attribute

using `schema.loads` on request.json seems to work 

alternately, why not have `data`, `relationships`, and `meta` as nested fields of the marshmallow jsonapi schema?

**Comment by rgant** [comment]
@jo-tham Can you point me to how you resolved this issue?

**Comment by jo-tham** [comment]
@rgant do you require webargs for your use case? 
I am just using `schema.load(request.json)`. It's one line, like the decorator, and sufficiently explicit.

Given a schema, webargs looks up values in request.json but it doesn't expect fields to be wrapped in the jsonapi envelope. You could try overriding `webargs.yourappparser.parse_json()` to deal with this.

**Comment by rgant** [comment]
I just started looking at the marshmallow ecosystem and I am trying to combine flask-restful API with marshmallow-jsonapi. Is there a good way to get the validation for a schema without using webargs?

For example, this is pretty convenient to handle validating args vs Schema:

```
# https://github.com/sloria/webargs/blob/dev/examples/schema_example.py
@app.route('/users/<int:user_id>', method=['POST'])
@use_args(UserSchema())
def post(args, user_id):
    ...
```

**Comment by jo-tham** [comment]
`UserSchema` extends `marshmallow-jsonapi.Schema`

note that i'm using flask-restful's class based view here

```
from flask import request

def post():
     post_args, errors = UserSchema.load(request.json)
     # ...
```

violations of the schema are available in `errors`

**Comment by rgant** [comment]
For jsonapi requests it would be more like `request.json['data']` right?

**Comment by jo-tham** [comment]
Nope, `marshmallow-jsonapi.Schema.load()` unwraps the object. So you should
can pass entire `request.json`

**Comment by rgant** [comment]
Thanks, I get it now. In webargs it expects to assemble the data (which might be from the query string) into a dict that can then be loaded into a Schema. But marshmallow-jsonapi expects the data to be in a very specific arrangement.
To work around this I did something like this:

``` python
import marshmallow as ma
from marshmallow import fields as ma_fields
import marshmallow_jsonapi as majapi
import webargs.core
import webargs.flaskparser


class JsonApiNested(ma.Schema):
    """ Placeholder wrapper for webargs to marshmallow-jsonapi handling. """
    # webargs.flaskparser.FlaskParser specifically returns missing if there is no json
    # at all instead of returning the field default
    data = ma_fields.Dict(required=True)  #, missing={}, default={})
    class Meta:  # pylint: disable=too-few-public-methods
        """ Sets strict so an error will be raised when invalid data is passed in. """
        strict = True


class JsonApiParser(webargs.flaskparser.FlaskParser):
    """ Special case handling for marshmallow-jsonapi.Schema's """
    def _parse_request(self, schema, req, locations):
        if isinstance(schema, majapi.Schema):
            jsonapi = JsonApiNested()
            data = super()._parse_request(jsonapi, req, locations)
            if data['data'] == webargs.core.missing:
                data = {}
        else:
            data = super()._parse_request(schema, req, locations)

        return data or {}

```

**Comment by DavidUnzue** [comment]
@rgant could you show how you integrated your custom parser with flask-restful's api?
How do you   tell `@use_args(UserSchema())` to use `JsonApiParser`?

**Comment by rgant** [comment]
@DavidUnzue I don't actually use `use_args` however that decorator is part of the base class for [`webargs.flaskparser.FlaskParser`](https://github.com/sloria/webargs/blob/dev/webargs/core.py#L390)

So you could use it via `@JsonApiParser.use_args` I believe. I haven't tried that.

**Comment by DavidUnzue** [comment]
Yes, that worked:

```
import JsonApiParser
# instantiate parser
json_api_parser = JsonApiParser()

@json_api_parser.use_args(MarshmallowSchema())
def post():
    ....
```

I noticed though, that the syntax for the `JsonApiParser` class is Python 3. For those using Python 2.7, change `super()` to `super(JsonApiParser, self)`.
