### ISSUE TITLE
Empty relationship

### ISSUE THREAD

**Issue by floqqi** [marshmallow-code/marshmallow-jsonapi#24]
How to handle empty relationship (e.g. nullable foreign key)?

Code in [line 55](https://github.com/marshmallow-code/marshmallow-jsonapi/blob/dev/marshmallow_jsonapi/flask.py#L55) currently results in:

```
werkzeug.routing.BuildError: Could not build url for endpoint '...'. Did you forget to specify values ['...']?
```

This is caused by an empty foreign key (-> `None` in `kwargs`) in the model of the my resource.

I have to work around with

``` python
if None in kwargs.values():
    return
```

after [line 53](https://github.com/marshmallow-code/marshmallow-jsonapi/blob/dev/marshmallow_jsonapi/flask.py#L53).

**Comment by floqqi** [comment]
Shortly thought that #14 would fix this issue, but it's sadly not working with the flask integration.

**Comment by jo-tham** [comment]
yes, #14 only addresses the data member of relationship objects.

i think your workaround is viable (i have also implemented it locally) and meets the jsonapi requirements when combined with result of #14. Do you wan to make a PR?

**Comment by floqqi** [comment]
Okay, I'm going to make a PR.

May it be a better solution to catch `werkzeug.routing.BuildError` instead of checking for `None`-values?

**Comment by jo-tham** [comment]
I think so - it's possible that the route has defaults that are used if a parameter is None, in which case no build error would be raised and we should get a valid link. 

On the other hand, (but this I'm not sure of) we may get a `BuildError` for other reasons and we want to let it raise.
You could verify that or perhaps just take the following approach, 

```
try the operation
catch the `BuildError`
if it's because of missing parameters, return None 
otherwise, raise()
```

sound OK?

**Comment by floqqi** [comment]
Sound's like the best solution. I'm going to make a PR soon.
