### ISSUE TITLE
Can this be available in Marshmallow itself?

### ISSUE THREAD

**Issue by Leo-G** [marshmallow-code/marshmallow-jsonapi#4]
Its a pain to look at the docs of two libraries and troubleshoot issues, can this be included a method of schema in marhmallow?

**Comment by sloria** [comment]
This will not be included in marshmallow core. marshmallow is not tied to any framework, specs, or even HTTP APIs at all. Also, it is more efficient to keep the development cycle of extensions independent of marshmallow core.
