### ISSUE TITLE
Schema without attributes can not be deserialized due to missing attributes key.

### ISSUE THREAD

**Issue by Dr-ZeeD** [marshmallow-code/marshmallow-jsonapi#42]
When I define my schema

``` python
class MyFirstSchema(Schema):
    id = fields.Int()

    class Meta:
        type_ = 'firsts'
```

and then try to load it like this

``` python
data = {'data': {'id': 1, 'type': 'firsts'}}
MyFirstSchema().load(data)


```

I get the following error:

```
marshmallow.exceptions.ValidationError: `data` object must include `attributes` key.
```

I do, however, not find any specification in JSON API saying that the `attributes` key has to be present.

Here is a full example:

``` python
from marshmallow_jsonapi import Schema, fields

class MyFirstSchema(Schema):
    id = fields.Int()

    class Meta:
        type_ = 'firsts'

data = {'data': {'id': 1, 'type': 'firsts'}}
MyFirstSchema().load(data)
```

**Comment by rgant** [comment]
This is also a problem for me trying to write endpoints for relationships which don't have attributes.

http://jsonapi.org/format/#document-resource-object-relationships

It's also a problem that unwrap_data doesn't load the id from the item which is the important part of the data for relationships.

**Comment by rgant** [comment]
I've overwritten the unwrap_item function for my `RelationshipSchema`s to work with Schemas that don't have attributes and need to know the IDs. @ZeeD26 I think this would work for your situation (I'm using python3, if you aren't you will need to convert the `super` to python2):

``` python
class MyFirstSchema(Schema):
    id = fields.Int()

    class Meta:
        type_ = 'firsts'

    def unwrap_item(self, item):
        """ Overload this function from marshmallow-jsonapi so it actually stores the id. """
        # Work around for ma-jsonapi requiring attributes when loading data.
        if 'attributes' not in item:
            item['attributes'] = {}
        payload = super().unwrap_item(item)
        # Work around for ma-jsonapi not loading the ids
        payload['id'] = item['id']
        return payload
```

You might want to change your id to a String as JSON API says that all ids should be strings: http://jsonapi.org/format/#document-resource-object-identification

**Comment by Dr-ZeeD** [comment]
Thank you @rgant for this workaround. Looking at the current implementation of `unwrap_item` it seems that an empty dictionary is already implemented as a fallback option in case the `attribute` key does not exist. All it would take is to delete the statement checking whether `attributes` is in the item.

``` python
    def unwrap_item(self, item):
        if 'type' not in item:
            raise ma.ValidationError('`data` object must include `type` key.')
        if item['type'] != self.opts.type_:
            raise IncorrectTypeError(actual=item['type'], expected=self.opts.type_)
        if 'attributes' not in item:
            raise ma.ValidationError('`data` object must include `attributes` key.')

        payload = self.dict_class()
        for key, value in iteritems(item.get('attributes', {})):
            payload[key] = value
        for key, value in iteritems(item.get('relationships', {})):
            payload[key] = value
        return payload
```

Regarding the id: Considering there are some people (at least me) who want to use this schema to implement a RESTful API to a database where integers are more common for `id`s than strings, shouldn't there be an "intrinsic" way to serialize to a string and deserialize to an integer (or whatever the field type is)?

**Comment by rgant** [comment]
I guess you could do something like:

``` python
    id = maja_fields.String(dump_only=True)  # pylint: disable=invalid-name
    id_ = maja_fields.Int(load_only=True, load_from='id')
```

I haven't tested that. 

I think the rational is:
1. URLs are strings
2. UUIDs are neat
3. Some people think that sequential ids are bad: http://blogs.perl.org/users/ovid/2014/11/stop-putting-auto-increment-ids-in-urls.html

**Comment by Dr-ZeeD** [comment]
Thank you once again!
But considering marshmallow and all its plugins try to be as agnostic as possible I would still like to see some "automagic" happen by default.

The article you link to makes a nice point – eventually I want to use slugs for the urls so I should be fine, but I'll keep it in mind for further projects :)

**Comment by rgant** [comment]
Well, I'll be. Maybe this is what you are looking for: `as_string`.

http://marshmallow.readthedocs.org/en/latest/api_reference.html#marshmallow.fields.Number

**Comment by cmanallen** [comment]
I addressed this as part of the bulk request pull [1].
1. https://github.com/marshmallow-code/marshmallow-jsonapi/pull/39/files#diff-b7695ff9c3cc7a719a2b771764c10302L108

**Comment by Dr-ZeeD** [comment]
Ah, I'm sorry for not seeing your pull request -- should I leave this issue open until it is pulled and merged?

**Comment by cmanallen** [comment]
@ZeeD26 I would leave it up.  If the pull isn't merged its good to have the issue still open so the author knows it is a desired feature.
