### ISSUE TITLE
Dynamic `type_` in schema during serialization

### ISSUE THREAD

**Issue by aalvrz** [marshmallow-code/marshmallow-jsonapi#421]
I am currently dealing with a result collection that contains different "types" of objects, a union of queries. This means that I cannot set a `type_` field to the schema's meta, it must be determined at run time when checking each object to be serialized.

I tried the following without any luck:

```python
class MySchema:
    class Meta:
        type_ = "foo"  # Should be overriden later
        strict = True

    @pre_dump
    def set_type(self, obj, **kwargs):
        self.opts.type_ = "fizz" if bool(obj.is_something) else "buzz"
        return obj
```

Serializing the collection of objects results in "buzz" being set as the type for all of them.

Help is appreciated

**Comment by Battlesheepu** [comment]
Hi again @aalvrz !

Correct me if I'm wrong, but you have a way to recognise which object is of what "type" - is that correct?

If that's how it is, why not:

1. Prepare separate schemas for each type (nothing dynamic here)
2. Loop through the results of the query, identifying the object's type
3. Choose the appropriate schema for serialization for every object and/or group objects together based on the type and /then/ serialize them en masse

I think it's a lot cleaner than dynamic types.
