### ISSUE TITLE
Why do you stringify the id of the resource_linkage ?

### ISSUE THREAD

**Issue by vamonte** [marshmallow-code/marshmallow-jsonapi#423]
Hi,

I have a question about the resource linkage. 
I use your code in my project and I don't understood  why my resource linkage id was always a string.
I checked your repository and I found the reason but I don't it.
In the fields.Relationship class, you stringify the id value to build the resource linkage. https://github.com/marshmallow-code/marshmallow-jsonapi/blob/e7273b4c3e6b7bad6279302caef2a87c96fbb785/marshmallow_jsonapi/fields.py#L182

I checked the jsonapi spec and I didn't find nothing about this.

Can you explain me why do you stringify the id ?
If there isn't a specific reason, I will do one PR to fix it.

Thank's for your work

**Comment by judgeaxl** [comment]
"Every [resource object](https://jsonapi.org/format/#document-resource-objects) MUST contain an id member and a type member. The values of the id and type members MUST be strings."

https://jsonapi.org/format/#document-resource-object-identification

**Comment by vamonte** [comment]
@judgeaxl Oh, I didn't see this part of the spec.
Thank's you for the link.
