### ISSUE TITLE
Throw error when `id` field is an integer?

### ISSUE THREAD

**Issue by Dr-ZeeD** [marshmallow-code/marshmallow-jsonapi#48]
When a model requires the use of integer based IDs the behavior desired by JSON API is to use strings anyway. Thus I use the `as_string` option in my schema definition. For dumping data everything works like a charm, also for loading -- except for an edge case: If the client sends a resource object with an integer ID marshmallow is smart enough to deal with this -- but JSON API requires the use of strings. Hence validation of the `id` should include checking whether it is a string or not. As far as I understand this is not possible with the method based validation approach (`validates(field_name)` decorator) as the conversion from string to integer already took place and the original data is not available. It is, however, available with the `validates_shema` decorator. If I use it like this

``` python
@validates_schema(pass_original=True)
def check_whether_id_is_a_string(self, data, original_data):
    if not isinstance(original_data['data']['id'], str):
        raise ValidationError('`id` object must be of type `string`.', 'id')
```

the error message gets formatted like this

```
{
    'errors': [
        {
            'detail': '`id` object must be of type `string`.',
            'source': {
                'pointer': '/data/attributes/id'
            }
        }
    ]
}
```

So as you can see the pointer points to the wrong level.

My question hence is: Is there a proper way to do this already, or should I try to set something up within the `format_error` method of the Schema class that incorporates another if clause checking whether the field name is `id`?

**Comment by sloria** [comment]
You can pass a dictionary to `ValidationError` containing the correct pointer:

``` python
            raise ValidationError([
                {
                    'detail': '`id` object must be of type `string`.',
                    'source': {
                        'pointer': '/data/id'
                    }
                }
            ])
```

**Comment by Dr-ZeeD** [comment]
Unfortunately this does not seem to work, the result I get is

``` json
{
    "errors": [
        {
            "detail": {
                "detail": "Required and provided IDs do not match.",
                "source": {
                    "pointer": "/data/id"
                }
            },
            "source": {
                "pointer": "/data/attributes/id"
            }
        }
    ]
}
```

**Comment by RazerM** [comment]
@ZeeD26, @sloria said "pass a dictionary" but looks like they accidentally put it in a list in their example. This works:

```python
raise ValidationError(
    {
        'detail': '`id` object must be of type `string`.',
        'source': {
            'pointer': '/data/id'
        }
    }
)
```

**Comment by scottwernervt** [comment]
There is a related discussion on the pull request marshmallow-code/marshmallow#755.
