### ISSUE TITLE
marshmallow in dev-requirements.txt

### ISSUE THREAD

**Issue by asteinlein** [marshmallow-code/marshmallow-jsonapi#50]
Shouldn't marshmallow itself be in `dev-requirements.txt`? I set up a fresh development environment according to the contributing guidelines, but that doesn't give me marshmallow which makes the tests fail.

I'll happily provide the PR to either update the guidelines or add the requirement, but I'm just unsure what the intention is.

**Comment by sloria** [comment]
Marshmallow is specified as a dependency of this package in `setup.py`, so it will get installed when you run

```
pip install -e .
```

which is documented in the contributing guidelines.
