### ISSUE TITLE
Relationship field `id` serialization and linkage

### ISSUE THREAD

**Issue by aholik** [marshmallow-code/marshmallow-jsonapi#53]
I use [hashids](http://hashids.org/) to encode ID values when serializing objects. The most straightforward way to doing this seemed to me to declare ID field using `fields.Method`. However when serializing a `Relationship` field then it picks up ID value straight from the source object instead of obtaining it through the schema`s ID field.

Example code:

``` python
from marshmallow import pprint
from marshmallow_jsonapi import Schema, fields

class BaseSchema(Schema):
    id = fields.Method('serialize_id', dump_only=True)

    def serialize_id(self, obj):
        # faking hashids.encode()
        return "%s+%s"%(self.opts.type_, obj['id'])

class CarSchema(BaseSchema):
    class Meta:
        type_ = 'cars'
        self_url = '/cars/{id}'
        self_url_kwargs = { 'id': '<id>' }

    name = fields.Str()
    parts = fields.Relationship(
        many=True,
        self_url='/cars/{id}/parts',
        self_url_kwargs={'id': '<id>'},
        include_resource_linkage=True,
        type_="parts",
        schema="PartSchema",
        required=True)

class PartSchema(BaseSchema):
    class Meta:
        type_ = 'parts'
        self_url = '/parts/{id}'
        self_url_kwargs = { 'id': '<id>' }

    name = fields.Str()

data = {
    'id': '0',
    'name': 'tesla',
    'parts': [
        {'id': '10', 'name': 'battery'}
    ]
}

pprint(CarSchema().dump(data).data)

{'attributes': {'name': 'tesla'},
 'id': 'cars+0',
 'links': {'self': '/cars/cars+0'},
 'relationships': {'parts': {'data': [{'id': '10', 'type': 'parts'}],
                             'links': {'self': '/cars/0/parts'}}},
 'type': 'cars'}
```

I would expect that `relationships.parts.links.self` should equal to `/cars/cars+0` and the related part ID `10` should equal to `parts+10` since `schema` is specified on the `parts` relationship field. Or is this an expected serialization behavior?

**Comment by jannis-a** [comment]
`python
self_url_kwargs = { 'id': '<id>' }`

The '<id>' indicates to pull the attribute named "id" from the instance. I'm not sure if you can pass the method to self_url_kwargs. 

One way you could go is defining that serialize_id method on your model (the model then needs the type_ information) and another method on your schema which then calls the model method. Maybe there's a better approach. :)
