### ISSUE TITLE
"Type" validation?

### ISSUE THREAD

**Issue by taion** [marshmallow-code/marshmallow-jsonapi#6]
Do you plan to validate item `type`s as part of your schema definition? The JSON API spec requires raising a 409 when there is a `type` mismatch. A nice way to handle this might be with a custom exception type (that subclasses `ValueError` instead of `ValidationError`) that applications can catch and re-raise as a 409 (it'd be a bit tricker to figure this out from a generic `ValidationError`).

**Comment by taion** [comment]
BTW, I can understand why it's `type_`, but feel like it'd still be better if it were `type` :p

**Comment by sloria** [comment]
Yes, I do plan on adding type validation. Deserialization/validation for this library still needs some work. Ideally, a schema would take be able to JSON API-formatted request body as input.

I'm -0 on `type`. I just decided to go with the PEP8 recommendation. ¯\_(ツ)_/¯

**Comment by sloria** [comment]
I agree, raising a custom subclass of ValidationError would be ideal. I am trying to get this to work in https://github.com/marshmallow-code/marshmallow/issues/284 , but it's tricky to get right with marshmallow's "error bundling" (due to ValidationErrors getting reraised during deserialization).

**Comment by taion** [comment]
The trailing underscore recommendation in PEP8 is for avoiding conflicts with keywords, e.g. for `class_`, rather than to avoid shadowing built-ins.

I feel like for something like a class attribute, it's not quite so bad, since in practice you don't shadow the built-in except for declaring other class attributes. For example, this doesn't trigger `redefined-builtin` in pylint (flake8's checks don't cover this at all).

**Comment by taion** [comment]
@sloria 

Sorry, what I meant was that the most straightforward approach would be to _not_ subclass `ValidationError`. To me it's actually somewhat defensible, because of the special case handling for this in the JSON API spec, which explicitly says to return a 409, rather than the 400 or 422 that you would get for normal validation failures.

**Comment by sloria** [comment]
Ah, sorry, I misunderstood your original post. Yes, I think using an error that doesn't subclass ValidationError would be a fine solution.

re: type--Fair point. I still slightly lean towards `type_` just because it's simpler to follow the blanket rule of always adding a trailing underscore to any variable that would mask a built-in or keyword--you don't have to think about class variables vs instance attributes vs. keywords vs. builtins. Also, syntax highlighting breaks with `type`.

But again, I don't feel strongly about it, so I'd be open to changing it if you think it improves usability.

**Comment by taion** [comment]
I'm fine either way.

I've definitely bitten myself repeatedly by using `id` as a variable name (for, uhh, IDs), so there's that.

**Comment by sloria** [comment]
This has been added.

**Comment by taion** [comment]
Thanks!
