### ISSUE TITLE
Drop top level links container when self_url is empty

### ISSUE THREAD

**Issue by ghost** [marshmallow-code/marshmallow-jsonapi#62]
This line seems to always evaluate to True: https://github.com/marshmallow-code/marshmallow-jsonapi/blob/dev/marshmallow_jsonapi/schema.py#L317. In the `many` case with `self_url_many` beeing *not set*, I exepect that the top level link is dropped like so:
```
diff --git a/marshmallow_jsonapi/schema.py b/marshmallow_jsonapi/schema.py
index d276baa..1f9db81 100644
--- a/marshmallow_jsonapi/schema.py
+++ b/marshmallow_jsonapi/schema.py
@@ -299,7 +299,10 @@ class Schema(ma.Schema):
             if self.opts.self_url:
                 self_link = data.get('links', {}).get('self', None)
 
-        return {'self': self_link}
+        if self_link:
+            return {'self': self_link}
+
+        return None
 
     def get_resource_links(self, item):
         """Hook for adding links to a resource object."""
```

**Comment by rgant** [comment]
@cudos I've provided a fix for this issue in #60:

https://github.com/marshmallow-code/marshmallow-jsonapi/pull/60/commits/b9a1c0b1b8a7018942ce0d78ddcf6528d60d530d

**Comment by rgant** [comment]
#60 is merged, so this can probably be closed.

**Comment by scottwernervt** [comment]
#60
