### ISSUE TITLE
How do I add self links

### ISSUE THREAD

**Issue by Leo-G** [marshmallow-code/marshmallow-jsonapi#7]
I see a function 
      def get_top_level_links(self, data, many):
        """Hook for adding links to the root of the response data."""
        return None

But i am not sure how to use it to get self links, any help will be apreciated?

**Comment by Meph-** [comment]
Look at the example:
https://github.com/marshmallow-code/marshmallow-jsonapi/blob/master/examples/flask_example.py

**Comment by Leo-G** [comment]
Thanks
