### ISSUE TITLE
Dependency error with Marshmallow>=2.3.0

### ISSUE THREAD

**Issue by jasonmotylinski** [marshmallow-code/marshmallow-jsonapi#70]
We ran into a weird issue when using marshmallow-jsonapi pulling in an incompatible version of marshmallow. In setup.py marshmallow-jsonapi requires marshmallow>=2.3.0. We found that this was pulling in the recently released 3.0 release of marshmallow, which is not compatible with marshmallow-jsoonapi. 

To fix the issue we added a hard dependency on marshmallow==2.13.0 to our requirements.txt. 

Can the dependency on marshmallow version be set to a compatible version or have marshallow-jsonapi updated to work with the 3.0 release of marshmallow?

**Comment by sloria** [comment]
Thanks for reporting, and sorry for the inconvenience. 

If I were to guess, this is actually an incompatibility with the changes 2.13.2, which was just released: https://github.com/marshmallow-code/marshmallow/issues/597 . We're working to resolve the issue. For now, pinning to 2.13.0 or 2.13.1 should work with marshmallow-jsonapi.

**Comment by sloria** [comment]
@jasonmotylinski FYI, marshmallow-jsonapi has been updated for compatibility with marshmallow 3.x.
