### ISSUE TITLE
Support "link objects"

### ISSUE THREAD

**Issue by danpoland** [marshmallow-code/marshmallow-jsonapi#72]
From http://jsonapi.org/format/#document-links:

### Each member of a links object is a “link”. A link MUST be represented as either:

- a containing the link’s URL.
- an object (“link object”) which can contain the following members:
href: a string containing the link’s URL.
meta: a meta object containing non-standard meta-information about the link.

Currently the library supports the first option but not the second. I will be creating a PR for the second, I just wanted to create a ticket to reference first.

**Comment by multimeric** [comment]
This can probably be closed...?

**Comment by GuillaumeCisco** [comment]
Is it supported today?
Can't find anything in the documentation :/
