### ISSUE TITLE
Schema.format_error incorrectly checks if index is falsely, when 0 (zero) is a valid index 

### ISSUE THREAD

**Issue by danpoland** [marshmallow-code/marshmallow-jsonapi#76]
Schema.format_error incorrectly checks if index is falsely, when 0 (zero) is a valid index and should be used when formatting the pointer.

**Comment by sloria** [comment]
Thanks @danpoland for reporting. I would gladly review and merge a fix for this.

**Comment by danpoland** [comment]
https://github.com/marshmallow-code/marshmallow-jsonapi/pull/77
