### ISSUE TITLE
Docs: Define `article` in quickstart examples

### ISSUE THREAD

**Issue by thorbjornwolf** [marshmallow-code/marshmallow-jsonapi#86]
The quickstart section of the docs ([readthedocs](http://marshmallow-jsonapi.readthedocs.io/en/latest/quickstart.html#serialization) and [in the repo](https://github.com/marshmallow-code/marshmallow-jsonapi/blob/dev/docs/quickstart.rst#serialization)) show some neat examples using an undefined object named `article`. 

For clarity (and so I'm sure I understand what is going on), it would be nice to have a definition of `article`.

**Comment by sloria** [comment]
This was fixed in https://github.com/marshmallow-code/marshmallow-jsonapi/pull/122
