### ISSUE TITLE
How to apply a database filter to an included relationship?

### ISSUE THREAD

**Issue by michaelgodshall** [marshmallow-code/marshmallow-jsonapi#87]
My include api request looks like this: `http://127.0.0.1:5000/api/products?include=favorites`

It's working correctly and includes favorites for products in the payload.  However, I'd like to only include favorites for products that the current user has favorited.  Where is the right place to set this up?  I've looked through the source code quite a bit and can't seem to find the right way to filter the database query for the included `favorites` relationship (using SqlAlchemy).  Any recommendations on how to approach this?

**Comment by scottwernervt** [comment]
I would setup a [many to many relationship](http://docs.sqlalchemy.org/en/latest/orm/basic_relationships.html#many-to-many) between user and products to track favorites. SQLAlchemy will handle the logic and allow you to easily iterate, add, and remove from `user.favorites`. Note: I use an endpoint `/api/user/me` to handle all requests related to the current user.

```python
user_favorites_table = Table(
    'user_favorites', Base.metadata,
    Column('id', BigInteger, primary_key=True),
    Column('user_id', BigInteger, ForeignKey('user.id', ondelete='cascade')),
    Column('product_id', BigInteger, ForeignKey('product.id', ondelete='cascade')),
    UniqueConstraint('user_id', 'product_id')
)

class UserModel(db.Model):
    favorites = relationship('ProductModel', secondary=user_favorites_table)
```

Next, add the `favorites` relationship to the user schema to support [compound documents](https://marshmallow-jsonapi.readthedocs.io/en/latest/quickstart.html#compound-documents):

```python
class User(Schema):
    id = fields.String()
    favorites = Relationship(type_='products', schema='ProductSchema', many=True)

    class Meta:
        type_ = 'users'
```
The endpoint for the current user's favorite products would be: `/api/user/me?include=favorites`.
