### ISSUE TITLE
If a request does not include all of the attributes for a resource, the server MUST interpret the missing attributes as if they were included with their current values. 

### ISSUE THREAD

**Issue by Leo-G** [marshmallow-code/marshmallow-jsonapi#9]
I am struggling to implement this my code 

```
      def patch(self, id):
             user = Users.query.get_or_404(id)
             raw_dict = request.get_json(force=True)
             user_dict = raw_dict['data']['attributes']
             try:
                 for key, value in user_dict.items():
                 schema.validate({key:value})
                 setattr(user, key, value)

             user.update()            
             return self.get(id)
```

Complete code at https://github.com/Leo-G/Flask-CRUD-API/blob/master/app/users/views.py

**Comment by Meph-** [comment]
I do not understand the issue. Server does not set the missing parameters to null , it will change only attributes that were sent in the request, right?

**Comment by Leo-G** [comment]
When I exclude an attribute for example let's say  a user resource has attributes name, email and phone, When I exclude the attribute email in the patch request Flask gives me a an error "The browser (or proxy) sent a request that this server could not understand."  I think this is because of schema validation but I am not sure. As per the JSON API spec it should not return an error it should use the existing data instead, So how can I achieve this?

**Comment by Meph-** [comment]
This code works for me:

    def patch(self, list_id):
        data = request.data
        serializer = serializer_list.load(data['data']['attributes'])
        data_to_update = serializer.data
        list = List.query.get(list_id)
        try:
            if data_to_update:
                for key, value in data_to_update.iteritems():
                    if hasattr(list, key):
                        setattr(list, key, value)
                db.session.commit()

        except Exception:
            db.session.rollback()
            raise

        serializer = serializer_list.dump(list)
        return serializer.data  # code 200

**Comment by Leo-G** [comment]
Let me check

**Comment by LeoJavaAI** [comment]
As per http://jsonapi.org/format/#crud-updating, while updating if the value is not there then it should use the current value.

How ever I am not able to achieve this, my code

```
raw_dict = request.get_json(force=True)
try:
    schema.validate(raw_dict)
    request_dict = raw_dict['data']['attributes']
    for key, value in request_dict.items():
        setattr(customer, key, value)
```

Now if in the schema class i declare a field as cannot be blank, then the above code will not let me interpret the missing field as current when I do an update without the field. How do I proceed?

**Comment by scottwernervt** [comment]
For CRUD updating, use the [partial loading](https://marshmallow.readthedocs.io/en/latest/quickstart.html#partial-loading),

```python
from marshmallow_jsonapi import Schema, fields

class Post:
    def __init__(self, id, title, body):
        self.id = id
        self.title = title
        self.body = body

    def __repr__(self):
        return '<Post(title={self.title!r} body={self.body!r})>'.format(self=self)

post = Post(id='1', title='Title', body='Original Body')

class PostSchema(Schema):
    id = fields.Str(dump_only=True)
    title = fields.Str(required=True)
    body = fields.Str()

    class Meta:
        type_ = 'posts'
        strict = True

post_schema = PostSchema()

input_data = {
    'data': {
        'type': 'posts',
        'attributes': {
            'body': 'New Body',
        }
    }
}

serialized = post_schema.load(input_data, partial=True)
for key, value in serialized.items():
    setattr(post, key, value)

print(post)
# <Post(title='Title' body='New Body')>
```
