### ISSUE TITLE
Serializing a collection of objects with top level meta object

### ISSUE THREAD

**Issue by aschatten** [marshmallow-code/marshmallow-jsonapi#95]
JSON API allows adding a top level meta object: http://jsonapi.org/format/#document-meta
```json
{
  "meta": {
    "copyright": "Copyright 2015 Example Corp.",
    "authors": [
      "Yehuda Katz",
      "Steve Klabnik",
      "Dan Gebhardt",
      "Tyler Kellen"
    ]
  },
  "data": {
    // ...
  }
}
```
Is there a way to do it in `marshmallow-jsonapi`? It seems like it's only allows to have a `meta` in Resource Objects.

**Comment by redlamb** [comment]
I just ran into this same issue and it does not appear to be supported out of the box. I solved it by extending ```marshmallow_jsonapi.Scheme``` and using a [context](http://marshmallow.readthedocs.io/en/latest/extending.html#using-context).

While I have yet to have a need to add links to the top-level object, this also addresses #96. However, note that this will clobber any automated links if the same name is used, e.g. "self", and urls have to be manually generated.

```
import json                                                                                           
from marshmallow_jsonapi import fields, Schema as _Schema                                             

class Schema(_Schema): 
    def wrap_response(self, data, many):                                                              
        ret = super(Schema, self).wrap_response(data, many)                                           
        if 'meta' in self.context:                                                                    
            ret['meta'] = self.context['meta']                                                        
        if 'links' in self.context:
            links = ret.setdefault('links', {})                                                       
            links.update(self.context['links'])                                                       
        return ret

class DomainSchema(Schema):
    id = fields.Number()                                                                              
    name = fields.String()

    class Meta(object):
        type_ = 'domain'                                                                              

domains = [ 
    {           
        'id': 1,                                                                                      
        'name': 'yahoo.com'
    },                                                                                                
    {       
        'id': 2,
        'name': 'google.com'
    }       
]

schema = DomainSchema(many=True)                                                                      
schema.context['meta'] = {                                                                            
    "copyright": "Copyright 2015 Example Corp.",                                                      
    "authors": [
      "Yehuda Katz",
      "Steve Klabnik",                                                                                
      "Dan Gebhardt",                                                                                 
      "Tyler Kellen" 
    ]       
}
schema.context['links'] = {                                                                           
    "next": "http://example.com/_search?page=2",                                                      
    "last": "http://example.com/_search?page=4"                                                       
}
result = schema.dump(domains)
print json.dumps(result.data, indent=4)
```

output:
```
{
    "meta": {
        "copyright": "Copyright 2015 Example Corp.", 
        "authors": [
            "Yehuda Katz", 
            "Steve Klabnik", 
            "Dan Gebhardt", 
            "Tyler Kellen"
        ]
    }, 
    "data": [
        {
            "attributes": {
                "name": "yahoo.com"
            }, 
            "type": "domain", 
            "id": 1.0
        }, 
        {
            "attributes": {
                "name": "google.com"
            }, 
            "type": "domain", 
            "id": 2.0
        }
    ], 
    "links": {
        "last": "http://example.com/_search?page=4", 
        "next": "http://example.com/_search?page=2"
    }
}
```

**Comment by scottwernervt** [comment]
@aschatten You can now use `fields.Meta()` (#56):

```python
from marshmallow_jsonapi import Schema, fields


class UserSchema(Schema):
    id = fields.Integer()
    metadata = fields.Meta()

    class Meta:
        type_ = 'user'


user_schema = UserSchema()
result = user_schema.dump({'id': 1, 'metadata': {'custom': 'text'}})
# {'data': {'type': 'user', 'id': 1, 'meta': {'custom': 'text'}}}
```

**Comment by swistakm** [comment]
@scottwernervt unfortunately this isn't a solution to the problem, as `meta` field should be a top-level property so it should be:
```python
{
    'data': {
        'type': 'user', 
        'id': 1,
    },
    'meta': {
        'custom':  'text'
    }
}
```
Instead of:
```python
{
    'data': {
        'type': 'user', 
        'id': 1,
        'meta': {
            'custom':  'text'
        }
    }
}
```

**Comment by rgant** [comment]
meta doesn't have to be top level, [it can also be part of a Resource Object](http://jsonapi.org/format/#document-resource-objects):

> In addition, a resource object MAY contain any of these top-level members:
> ...
> meta: a meta object containing non-standard meta-information about a resource that can not be represented as an attribute or relationship.

**Comment by swistakm** [comment]
@rgant good point about the spec. I was probably too much focused on typical uses for such "meta" objects in most APIs I've seen so fat.

So we have at least two kinds of meta in spec:
1. document-level meta (top-level key): it can be used to provide information specific for whole request/response like debug information, total count of documents for multiple resource responses, copyright/authors (as exemplified in this issue). Generally all information that isn't specific to single resource if multiple entities available as list and should not be duplicated in every resource.
2. resource-level meta: can be used to provide meta information that is specific only for single resource object.

So to cover both cases it would be best to have two separate meta fields. E.g. `metadata/resource_metadata` or `document_metadata/metadata`. I still don't know what are typical use cases for resource-level metadata as I cannot imagine resource-specific data that couldn't/shouldn't be expresses as attribute or relationship. Of course I don't claim it is completely useless. I just think that it is generally less relevant.

**Comment by rgant** [comment]
For me I need to have document level for the case where primary data is a list of resource objects (an array) I want to have specific meta information for each document, not the request as a whole.

```"python"
{'data': [{'attributes': {'name': 'Impossible Stand'},
          'id': '21',
          'links': {'self': '/persons/21'},
          'meta': {'modified_at': '2017-08-14T17:50:19+00:00'},
          'relationships': {'children': {'links': {'related': '/persons/21/children',
                                                   'self': '/persons/21/relationships/children'}},
                            'parent': {'links': {'related': '/persons/21/parent',
                                                 'self': '/persons/21/relationships/parent'}}},
          'type': 'persons'},
         {'attributes': {'name': 'Carry Cool'},
          'id': '22',
          'links': {'self': '/persons/22'},
          'meta': {'modified_at': '2017-08-14T17:50:19+00:00'},
          'relationships': {'children': {'links': {'related': '/persons/22/children',
                                                   'self': '/persons/22/relationships/children'}},
                            'parent': {'links': {'related': '/persons/22/parent',
                                                 'self': '/persons/22/relationships/parent'}}},
          'type': 'persons'}],
'links': {'self': '/persons/20/children'}}
```

I have been playing around with how to address this issue, but trying to create a generic solution that doesn't re-write all the Meta field work is hard. For me I want to have anything read-only about my model placed into the meta key on the resource object. I don't ever really want to desalinize meta information.

Any ideas would be welcome, perhaps we should create a new ticket.

**Comment by scottwernervt** [comment]
We could definitely support `document-level meta` and `resource-level meta` by bringing back the old code with the pull request. Would an option like `'is_resource` on the `Meta` field acceptable? Another option would be to have two separate fields: `MetaResource` and `MetaDocument`.

```python
class UserSchema(Schema):
    id = fields.Integer()
    meta_resource = fields.Meta(is_resource=True, dump_as='meta')
    meta_document = fields.Meta(dump_as='meta')

    class Meta:
        type_ = 'user'

```

**Comment by rgant** [comment]
I was playing with doing that, however I found that deserializing the data need a bunch of changes to `_META_LOAD_FROM` logic. It wasn't designed with the idea of two Meta fields.

Might want to continue this conversation in #107
