### ISSUE TITLE
How to optimize deep includes

### ISSUE THREAD

**Issue by FelixEnescu** [marshmallow-code/marshmallow-jsonapi#99]
Hi

We are using marshmallow-jsonapi with SQLAlchemy and we have few cases where we need to retrieve a groups of objects involving some deep includes. One such example is 

GET /v3/portfolios/672/investments?fields[accounts]=name&fields[files]=url&fields[indicators]=name&fields[investment_invitations]=organization&fields[reports]=name,stage,status&fields[results]=forecast_current&filter[allocations.results.indicator.relevant]=true&include=allocations.report,allocations.report.results,allocations.report.results.indicator,allocations.report.logo_file,invitation,grantee

The issues is that such calls takes ages.

I looked into `marshmallow-jsonapi` and understand how include data is gathered and how that can generate lot's of queries. 

I looked for ways to optimize that but did not see any obvious way to modify `fields.py`.

Any suggestion will be highly welcome.

**Comment by scottwernervt** [comment]
> I looked into marshmallow-jsonapi and understand how include data is gathered and how that can generate lot's of queries.

Are your model relationships being lazy loaded? The queries will not fire until marshmallow-jsonapi accesses the model attribute/relationship belonging to it. If you are constantly accessing the same relationships on a request, it would make sense to load the relationships with the parent.

1. Get a [benchmark](http://docs.sqlalchemy.org/en/latest/faq/performance.html) for each include relationship query.
2. Change the [relationship loading technique](http://docs.sqlalchemy.org/en/latest/orm/loading_relationships.html).
3. Add appropriate [indexes](http://docs.sqlalchemy.org/en/latest/core/constraints.html?highlight=index#indexes) for your attributes and relationship foreign keys.

**Comment by FelixEnescu** [comment]
Thanks a lot, very helpful.
